[theme]
base = "light"
primaryColor = "#4caf50"
backgroundColor = "#e0f7fa"
secondaryBackgroundColor = "#e8f5e9"
textColor = "#1a1a1a"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"
showSidebarNavigation = true
